### ISSUE TITLE
总结 用词 错误

### ISSUE THREAD

**Issue by jiefei666** [Esdiarap/vuejs3Code--HcySunYang-Ver.#3]
第九章 总结： 遍历新旧两组子节点中数量**较多**的那一组, 应该是： **较少** , 9.1 patchChildren 中代码是：  `commonLength = Math.min(oldLen, newLen)`

**Comment by Esdiarap** [comment]
对的。代码没有错（221页），241页的总结出错了。第五行应是遍历新旧两组子节点中数量较少的那一组。
可以去霍春阳的源码那里提issue。XD
