### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by jiefei666** [Esdiarap/vuejs3Code--HcySunYang-Ver.#4]
264 页 --> while 循环中 --> 第二个分支语句： `oldEndVNode  = newChildren[--oldEndIdx]` 应该为 ` oldEndVNode  = oldChildren[--oldEndIdx]`

**Comment by Esdiarap** [comment]
对的。可以去霍春阳原版的那里提这个issue，如果那边没有人提的话
